//SIGNUP
export const SIGNUP_POST_REQ = "SIGNUP_POST_REQ";
export const SIGNUP_POST_SUCCESS = "SIGNUP_POST_SUCCESS";
export const SIGNUP_POST_FAILURE = "SIGNUP_POST_FAILURE";
//LOGIN
export const LOGIN_POST_REQ = "LOGIN_POST_REQ";
export const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS";
export const LOGIN_POST_FAILURE = "LOGIN_POST_FAILURE";
