//GET REQ
export const NOTES_GET_REQ = "NOTES_GET_REQ";
export const NOTES_GET_SUCCESS = "NOTES_GET_SUCCESS";
export const NOTES_GET_FAILURE = "NOTES_GET_FAILURE";
//POST REQ
export const NOTES_POST_REQ = "NOTES_POST_REQ";
export const NOTES_POST_SUCCESS = "NOTES_POST_SUCCESS";
export const NOTES_POST_FAILURE = "NOTES_POST_FAILURE";
//PATCH REQ
export const NOTES_PUT_REQ = "NOTES_PUT_REQ";
export const NOTES_PUT_SUCCESS = "NOTES_PUT_SUCCESS";
export const NOTES_PUT_FAILURE = "NOTES_PUT_FAILURE";
//DELETE REQ
export const NOTES_DELETE_REQ = "NOTES_DELETE_REQ";
export const NOTES_DELETE_SUCCESS = "NOTES_DELETE_SUCCESS";
export const NOTES_DELETE_FAILURE = "NOTES_DELETE_FAILURE";
